// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs xls-to-xlsx`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "xlsx-viewer",
    "icon": "📗",
    "name": {
      "en": "Excel Workbook Viewer",
      "ja": "Excelビューア",
      "zh": "Excel 查看器",
      "de": "Excel-Arbeitsmappen-Viewer",
      "es": "Visor de libros de Excel"
    },
    "desc": {
      "en": "Open and browse an Excel workbook: switch sheets, no editing.",
      "ja": "Excelブックを開いて閲覧。シート切替、編集はしません。",
      "zh": "打开并浏览 Excel 工作簿，可切换工作表，不支持编辑。",
      "de": "Excel-Arbeitsmappe öffnen und ansehen, Blätter wechseln, keine Bearbeitung.",
      "es": "Abre y consulta un libro de Excel, cambia de hoja, sin edición."
    }
  },
  {
    "slug": "xlsx-to-csv",
    "icon": "📤",
    "name": {
      "en": "XLSX to CSV",
      "ja": "XLSX→CSV分割",
      "zh": "XLSX 转 CSV",
      "de": "XLSX zu CSV",
      "es": "XLSX a CSV"
    },
    "desc": {
      "en": "Split an Excel workbook into one CSV per sheet, zipped.",
      "ja": "Excelブックを1シート1CSVに分割してZIPで出力。",
      "zh": "将 Excel 工作簿按工作表拆分为多个 CSV，打包为 ZIP。",
      "de": "Teilt eine Excel-Arbeitsmappe in je eine CSV pro Blatt auf, als ZIP.",
      "es": "Divide un libro de Excel en un CSV por hoja, comprimido en ZIP."
    }
  },
  {
    "slug": "unlock-xlsx",
    "icon": "🔓",
    "name": {
      "en": "Remove Excel Sheet Protection",
      "ja": "Excelシート保護解除",
      "zh": "解除 Excel 工作表保护",
      "de": "Excel-Blattschutz entfernen",
      "es": "Quitar protección de hojas de Excel"
    },
    "desc": {
      "en": "Remove sheet and workbook editing protection from an XLSX/XLSM file you can already open.",
      "ja": "開けるExcelファイルのシート保護・ブック保護を解除。",
      "zh": "移除可正常打开的 XLSX/XLSM 文件中的工作表和工作簿保护。",
      "de": "Entfernt den Blatt- und Arbeitsmappenschutz aus einer bereits öffenbaren XLSX/XLSM-Datei.",
      "es": "Elimina la protección de hojas y de estructura de un archivo XLSX/XLSM que ya puedes abrir."
    }
  },
  {
    "slug": "strip-xlsx-metadata",
    "icon": "🧹",
    "name": {
      "en": "Strip XLSX Metadata",
      "ja": "Excelメタデータ削除",
      "zh": "清除 Excel 元数据",
      "de": "XLSX-Metadaten entfernen",
      "es": "Eliminar metadatos de XLSX"
    },
    "desc": {
      "en": "Remove author, company, and custom-property metadata from an Excel workbook.",
      "ja": "Excelブックの作成者・会社名・カスタムプロパティを削除。",
      "zh": "移除 Excel 工作簿中的作者、公司和自定义属性等元数据。",
      "de": "Entfernt Autor-, Firmen- und benutzerdefinierte Metadaten aus einer Excel-Arbeitsmappe.",
      "es": "Elimina el autor, la empresa y las propiedades personalizadas de un libro de Excel."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'xls-to-xlsx';
